<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>

		<LangVersion>latest</LangVersion>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>

		<PackageOutputPath>$(MSBuildThisFileDirectory)/nupkgs</PackageOutputPath>

    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	</PropertyGroup>
</Project>
