name: Build, Test, Publish

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
  release:    
    types: [published,edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.5.0
      with:
        versionSpec: '6.x'

    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v4.5.0

    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=${{ steps.gitversion.outputs.semVer }} 
    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
    - name: Publish
      if: github.event_name == 'release'
      shell: pwsh
      run: |
        Get-ChildItem ".\nupkgs" -Filter "*.*nupkg" -R | ForEach-Object {
          Write-Host "Pushing $($_.Name)"
          dotnet nuget push $_ --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
          if ($lastexitcode -ne 0) {
            throw ("Exec: " + $errorMessage)
          }
        }
